export { default as BasicPage } from "./basicPage.js"
export { default as Page } from "./page.js"
export { homePage } from "./homePage.js"
export { lessonsPage } from "./lessonsPage.js"
export { lessonPage } from "./lessonPage.js"
export { taskPage } from "./taskPage.js"
export { notFoundPage } from "./notFoundPage.js"
